### ISSUE TITLE
Cannot explore big kzb files.

### ISSUE THREAD

**Issue by AuRoN89** [theawesomecoder61/KZB-Explorer#1]
Hi, i tried use your tool to explore some kzb files, with most of them it works fine but with the big ones it doesn't.

130mb one and 50mb the other one.

The first one return this exception:

System.Exception: Not a valid KZB file.
   at KZB.KZBFile.Read()
   at KZB_Explorer.Form1.LoadFile(String file)
   at KZB_Explorer.Form1.openToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

The other instead, cause a 'freeze' of the app, and then a crash.

I also have a custom command line utility to unpack kzb, and it works fine with these kzb too, so the format is indeed valid.

**Comment by theawesomecoder61** [comment]
Hi. I appreciate you bringing this to my attention.

That error "Not a valid KZB file" happens when the first four bytes of a kzb file do not match the expected value (found in KZBFile.cs). Maybe that kzb file is newer or older than the files I tested with?

Does the 130 MB file crash the program?

If you do not mind (as it would help me tremendously), could you download the free hex editor software "HxD", open the 130 MB kzb in it, and take a screenshot of the first row of bytes?

I am currently in the process of issuing a new update, which I can notify you here when it is ready. In that update, I will change how files are loaded, and hopefully that will fix the 50 MB file that causes the crash.

Thank you.

**Comment by AuRoN89** [comment]
Hello, i'm really sorry for the late response, i just noticed there was a reply lol... my bad.

Yes, the 130MB file does cause a crash, but with the exception popup, while the 50mb one hang the app, and then crash it (without any error).

Below, the screenshot of the 130mb file.

![Image](https://github.com/user-attachments/assets/13cd8a15-9018-42ee-b45b-b7d2eb45f20c)

You were right about the file header... it looks different compared to the other kzb files, but, as i previously said, i also used custom command line tool and it can extract the content.

**Comment by zhenglishan** [comment]
<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/31ee6bf7-f6ef-42df-8395-36ce75cfb160" />I have also encountered the same problem. When I open the instrument background KZB file, I get an error message indicating that the KZB file is invalid. It would be great if this problem could be solved

**Comment by mbecoool** [comment]
>  i also used custom command line tool and it can extract the content.

Hello. Can you recommend a program for unpacking kzb?
